apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aria-agents.fullname" . }}
  labels:
    app: {{ include "aria-agents.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "aria-agents.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "aria-agents.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9520
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
          resources: {{ .Values.resources | toYaml }}