[project]
authors = ["gkreder <gkreder@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "aria-agents"
platforms = ["osx-arm64"]
version = "0.1.0"


[dependencies]
python = "3.10.13"

[pypi-dependencies]
schema_agents = { git = "https://github.com/aicell-lab/schema-agents.git" }
imjoy-rpc = "==0.5.48.post2"
requests = "==2.31.0"
pypdf = "==4.2.0"
pillow = "==10.3.0"
matplotlib = "==3.9.0"
hypha = "==0.15.50"
hypha-rpc = "==0.20.37"
tqdm = "==4.66.4"
aiofiles = "==23.2.1"
serpapi = "==0.1.5"
langchain = "==0.1.14"
langchain-community = ">=0.0.25"
langchain-core = "==0.1.46"
langchain-openai = "==0.1.7"
langchain-text-splitters = "==0.0.1"
langchain-experimental = "==0.0.56"
beautifulsoup4 = "==4.12.3"
rank-bm25 = "==0.2.2"
html2text = "==2020.1.16"
setuptools = "==70.0.0"
PyYAML = "==6.0.1"
llama-index = ">=0.11.14, <0.12"
llama-index-readers-papers = ">=0.2.0, <0.3"
pandasai = "==2.3.0"
