import dotenv
dotenv.load_dotenv()
import argparse
import os
import pandas as pd
from contextlib import redirect_stdout
from io import StringIO
import asyncio
from typing import List
import asyncio
import shutil
import dotenv
from schema_agents import schema_tool, Role
from pydantic import BaseModel, Field
from langchain_experimental.tools.python.tool import PythonAstREPLTool
from contextlib import redirect_stdout
from io import StringIO
import json

# Load the configuration file
this_dir = os.path.dirname(os.path.abspath(__file__))
config_file = os.path.join(this_dir, "config.json")
with open(config_file, "r") as file:
    CONFIG = json.load(file)

async def main():
    parser = argparse.ArgumentParser(description='Run hypothesis testing on experimental data')
    parser.add_argument('experiment_files', nargs='+', help='List of files to analyze')
    args = parser.parse_args()

    file_explorer = Role(
        name = "File Explorer",
        instructions = "You are a file explorer. You read given files generated by scientific experiments to get a sense of their content and structure",
        constraints = None,
        register_default_events = True,
        model = CONFIG['llm_model']

    )

    print(args.experiment_files)


    
    

if __name__ == "__main__":
    asyncio.run(main())



