apiVersion: apps/v1
kind: Deployment
metadata:
  name: aria-agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aria-agents
  template:
    metadata:
      labels:
        app: aria-agents
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: aria-agents
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 9520
          env:
            - name: SERVER_URL
              value: "{{ .Values.hypha.server_url }}"          # Correct reference to the server URL
            - name: WORKSPACE_NAME
              value: "{{ .Values.hypha.workspace }}"           # Correct reference to workspace name
            - name: CLIENT_ID
              value: "{{ .Values.CLIENT_ID }}"                  # Ensure CLIENT_ID is defined in values.yaml
            - name: SERVICE_ID
              value: "{{ .Values.SERVICE_ID }}"                 # Ensure SERVICE_ID is defined in values.yaml
            - name: WORKSPACE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aria-agents-secrets                    # Reference to the secret
                  key: WORKSPACE_TOKEN                          # Ensure the key exists in the secret
          command: ["python", "-m", "hypha_rpc.utils.serve", "main:app", "--id=aria-agents-service", "--name=Aria Agents Service", "--server-url={{ .Values.hypha.server_url }}", "--workspace={{ .Values.hypha.workspace }}", "--login"]  # Use Helm templating for server-url and workspace