name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt

    - name: Run tests
      env:
        TEST_HYPHA_TOKEN: ${{ secrets.TEST_HYPHA_TOKEN }}
        WORKSPACE_TOKEN: ${{ secrets.WORKSPACE_TOKEN }}
        WORKSPACE_NAME: ${{ secrets.WORKSPACE_NAME }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        pytest --asyncio-mode=auto
